# Generated by Django 6.0.1 on 2026-02-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_recruiterprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience_required',
        ),
        migrations.AddField(
            model_name='job',
            name='max_experience',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='min_experience',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
