from django.urls import path
from .views import *

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('protected/', ProtectedView.as_view(), name='protected'),
    path('recruiter/', RecruiterOnlyView.as_view(), name='recruiter'),
    path('candidate/', CandidateOnlyView.as_view(), name='candidate'),
    path('admin/', AdminOnlyView.as_view(), name='admin'),
    path('jobs/create/', RecruiterJobCreateView.as_view(), name='job_create'),
    path('jobs/my/', RecruiterJobListView.as_view(), name='job_list'),
    path('dashboard/', recruiter_dashboard, name='recruiter_dashboard'),
    path('jobs/create/ui/', job_create_ui, name='job_create_ui'),
    path('jobs/', candidate_job_list, name='candidate_job_list'),
    path('jobs/<int:job_id>/', job_detail, name='job_detail'),
    path('jobs/apply/<int:job_id>/', apply_to_job, name='apply_to_job'),
    path('candidate/dashboard/', candidate_dashboard, name='candidate_dashboard'),
    path('application/<int:application_id>/upload/',upload_resume,name='upload_resume'),
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('recruiters/', recruiters_page, name='recruiters'),
    path('candidates/', candidates_page, name='candidates'),
    path('redirect/', home_redirect, name='home_redirect'),
    path('admin-dashboard/', admin_dashboard, name='admin_dashboard'),
    path('admin/recruiters/', admin_recruiters, name='admin_recruiters'),
    path('admin/recruiter/verify/<int:pk>/', verify_recruiter, name='verify_recruiter'),
    path('admin/recruiter/delete/<int:pk>/', delete_recruiter, name='delete_recruiter'),
    path('admin/candidates/', admin_candidates, name='admin_candidates'),
    path('admin/candidate/delete/<int:pk>/', delete_candidate, name='delete_candidate'),
    path('admin/applications/', admin_applications, name='admin_applications'),
    path('admin/application/delete/<int:pk>/', delete_application, name='delete_application'),
    path('recruiter/job/<int:job_id>/applications/', recruiter_applications, name='recruiter_applications'),
    path('admin/recruiter/toggle/<int:pk>/', toggle_recruiter_status, name='toggle_recruiter_status'),
    path('admin/candidate/toggle/<int:pk>/', toggle_candidate_status, name='toggle_candidate_status'),
]
