# Generated by Django 5.0.4 on 2026-04-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='score',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='total_questions',
        ),
        migrations.AddField(
            model_name='testresult',
            name='final_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='mcq_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='mcq_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='output_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='output_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
