# Generated by Django 5.2.11 on 2026-02-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interviewquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiointerviewresponse',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='audiointerviewresponse',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='interview_videos/'),
        ),
    ]
