# Generated by Django 5.2.11 on 2026-03-09 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_remove_audiointerviewresponse_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiointerviewresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiointerviewresponse',
            name='emotion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='audiointerviewresponse',
            name='filler_words',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiointerviewresponse',
            name='speech_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
