# Generated by Django 5.2.1 on 2026-05-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_audiointerviewresponse_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiointerviewresponse',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='interviewquestion',
            options={'ordering': ['order']},
        ),
    ]
