# Generated by Django 5.0.4 on 2026-04-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_application_id_alter_job_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='test_completed',
            field=models.BooleanField(default=False),
        ),
    ]
