# Generated by Django 6.0.1 on 2026-02-28 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_remove_job_experience_required_job_max_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_threshold', models.FloatField(default=0.7)),
                ('skill_weight', models.FloatField(default=0.7)),
                ('experience_weight', models.FloatField(default=0.3)),
                ('min_final_score', models.FloatField(default=0.35)),
                ('semantic_weight', models.FloatField(default=0.5)),
                ('frequency_weight', models.FloatField(default=0.2)),
                ('context_weight', models.FloatField(default=0.2)),
                ('recency_weight', models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('anonymized_text', models.TextField(blank=True, null=True)),
                ('onsite_years', models.FloatField(blank=True, null=True)),
                ('remote_years', models.FloatField(blank=True, null=True)),
                ('adjusted_experience', models.FloatField(blank=True, null=True)),
                ('experience_score', models.FloatField(blank=True, null=True)),
                ('skill_score', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('resume_embedding', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.job')),
            ],
            options={
                'unique_together': {('candidate', 'job')},
            },
        ),
        migrations.CreateModel(
            name='SkillMatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_skill', models.CharField(max_length=255)),
                ('best_sentence', models.TextField(blank=True, null=True)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('frequency_score', models.FloatField(blank=True, null=True)),
                ('context_score', models.FloatField(blank=True, null=True)),
                ('recency_score', models.FloatField(blank=True, null=True)),
                ('skill_strength', models.FloatField(blank=True, null=True)),
                ('sentence_embedding', models.JSONField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_details', to='resume_engine.resumeapplication')),
            ],
        ),
    ]
