# Generated by Django 6.0.1 on 2026-02-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillmatchdetail',
            name='application',
        ),
        migrations.DeleteModel(
            name='ResumeApplication',
        ),
        migrations.DeleteModel(
            name='SkillMatchDetail',
        ),
    ]
