# Generated by Django 5.0.4 on 2026-04-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_engine', '0002_remove_skillmatchdetail_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
